### ISSUE TITLE
[BUG] Two Types of Copper Tools/Armor

### ISSUE THREAD

**Issue by puncrafter** [MrAwesomeRocks/the-latest-summer-fun-with-diary#12]
**Describe the bug**

There is some content overlap with two types of copper tools/armor. One from Tools Complement and one from Create Stuff Additions.

**Expected behavior**

There should be one set. I don't care which one you keep.

**Where is this bug happening? Check all that apply.**

- [x] Singleplayer
- [ ] Multiplayer
- [ ] Game load
- [ ] Other: **FILL HERE**

---

Who would you like to work on this issue?

- [ ] Yourself (i.e. you send in a PR)
- [x] Anyone

**Comment by egelja** [comment]
Which textures do you like better?
